ImMin5/barrier-free

.gitignore
src/main/webapp/WEB-INF/views/home.jsp

- .gitignore 수정
- application-dev와 java를 사용할 시 필요없는 파일 제외 목록 작성

[DOCS] Edit gitignore

---

src/main/java/com/team/bf/HomeController.java
src/main/java/com/team/bf/controller/AccommodationController.java
src/main/java/com/team/bf/controller/BoardController.java
src/main/java/com/team/bf/controller/DiscountController.java
src/main/java/com/team/bf/controller/MapAndPlannerController.java
src/main/java/com/team/bf/controller/MemberController.java
src/main/java/com/team/bf/controller/TourLocationController.java

- feature/openapi -> develop
-  지도/플래너너, 회원정보, 게시판, 여행지정보  관련 뷰페이지를 컨트롤러에 연결
- 없음

[FEAT] 뷰페이지 매핑 

---

src/main/java/com/team/bf/controller/AccommodationController.java
src/main/java/com/team/bf/controller/MemberController.java
src/main/java/com/team/bf/controller/SuggestionController.java
src/main/java/com/team/bf/dao/MemberDAO.java
src/main/java/com/team/bf/dao/SuggestionDAO.java
src/main/java/com/team/bf/service/MemberService.java
src/main/java/com/team/bf/service/MemberServiceImpl.java
src/main/java/com/team/bf/service/SuggestionService.java
src/main/java/com/team/bf/service/SuggestionServiceImpl.java
src/main/java/com/team/bf/vo/PagingVO.java
src/main/java/com/team/bf/vo/SuggestionVO.java
src/main/resources/mapper/memberMapper.xml

- feature/member -> develop
-  로그인 회원탈퇴 기능 구현
-  숙박정보 뷰페이지에서 파라미터 존재 여부에 따른 기본값 설정변경
- 없음

[FEAT] 로그인 회원탈퇴 기능 api 작성 close #19

---

src/main/java/com/team/bf/controller/MemberController.java
src/main/java/com/team/bf/dao/MemberDAO.java
src/main/java/com/team/bf/service/MemberService.java
src/main/java/com/team/bf/service/MemberServiceImpl.java
src/main/resources/mapper/memberMapper.xml

- [] 버그 수정
- feature/signup -> develop
-  회원가입시 아이디 중복검사 기능 api 구현
- 없음

[FEAT] 아이디 중복검사 기능

---

src/main/webapp/WEB-INF/inc/bottom.jsp
src/main/webapp/css/bottom.css

feature/main -> develop
- bottom CSS 수정
- 없음

[FEAT]bottom CSS수정

---

src/main/java/com/team/bf/controller/MapAndPlannerController.java
src/main/java/com/team/bf/dao/ReviewDAO.java
src/main/java/com/team/bf/service/OpenApiService.java
src/main/java/com/team/bf/service/ReviewService.java
src/main/resources/mapper/reviewMapper.xml

feature/map_planner -> develop
- OpenApiService의 detailCommon 매개변수 및 return값 수정
- MapAndPlannerController.java -> mapView의 tourList에 overview, firstimage,firstimage2, likeCount, heartCount, reviewCount, scoreAvg 데이터 추가

[FEAT] OpenApiService detailCommon 파라미터 변경 및 로직 수정 close #55

---

src/main/java/com/team/bf/controller/BoardController.java
src/main/java/com/team/bf/controller/MapAndPlannerController.java

feature/map_planner -> develop
- mapView.jsp에 전달될 JSONObject에 homepage 데이터 추가
- myreview 페이지 연결 url 중복 맵핑 수정

mypage url중복선언 수정 및 mapView.jsp에 hompage 데이터 추가

---

src/main/resources/mapper/boardMapper.xml

-  boardMapper.xml에 boardAndReplySelectAll 수정 -> select에 userid 추가 where에 is_notice=false 추가

boardMapper.xml->boardAndReplySelectAll에 select userid 추가 및 공지사항 close #70

---

src/main/java/com/team/bf/controller/AccommodationController.java
src/main/java/com/team/bf/service/OpenApiService.java

feature/openapi-> develop
- OpenApiService 지역코드 조회 기능 추가
-

OpenApiService 지역코드 조회 기능 추가

---

src/main/java/com/team/bf/controller/BoardController.java
src/main/webapp/WEB-INF/views/community/board.jsp
src/main/webapp/WEB-INF/views/community/boardDetail.jsp
src/main/webapp/WEB-INF/views/community/boardEdit.jsp
src/main/webapp/WEB-INF/views/community/boardForm.jsp

feature/boardView-> develop
- 문의공지사항/ 수정
-

[FEAT]문의/공지사항 수정

---

src/main/java/com/team/bf/controller/MapAndPlannerController.java
src/main/java/com/team/bf/dao/PlannerDAO.java
src/main/java/com/team/bf/service/PlannerService.java
src/main/java/com/team/bf/service/PlannerServiceImpl.java
src/main/java/com/team/bf/vo/PlannerLocationVO.java
src/main/java/com/team/bf/vo/PlannerMemberVO.java
src/main/java/com/team/bf/vo/PlannerVO.java
src/main/resources/mapper/plannerMapper.xml

- PlannerVO,DAO,Service 생성
- mapView에 reviewCount 데이터 타입 변경 Object->int
- 여행 플래너 생성 기능 추가
-

MapAndPlannerController에서 reviewCount수정, 평점으로 뜨게 수정

---

src/main/java/com/team/bf/controller/BoardController.java
src/main/java/com/team/bf/controller/MemberController.java
src/main/resources/mapper/boardMapper.xml

- [] 기능 추가
- boardMapper.xml selectByNo에 content데이터 추가
- boardDetailView 연결
- 회원 탈퇴 view 페이지 연결
-

boardMapper.xml selectByNo에서 content 데이터 추가 및 페이지 연결

---

src/main/java/com/team/bf/controller/BoardController.java
src/main/java/com/team/bf/controller/MemberController.java

-  마이페이지 뷰에 유저정보 데이터 객체 mvo 추가
-

마이페이에지 뷰에 유저정보 데이터 객체 mvo추가 close #88

---

src/main/webapp/WEB-INF/views/map/mapView.jsp
src/main/webapp/css/mapstyle.css

feature/map-> develop
-  mapView 검색창에서 키워드 검색시 해당 단어가 들어간 장소 검색기능 구현
-

[FEAT]map 검색기능 추가

---

src/main/webapp/WEB-INF/views/community/board.jsp
src/main/webapp/WEB-INF/views/community/boardDetail.jsp
src/main/webapp/WEB-INF/views/community/boardEdit.jsp
src/main/webapp/WEB-INF/views/community/boardForm.jsp

feature/boardView-> develop
-  공지/문의사항 게시글 수정/삭제 기능 추가
-

[FEAT]공지/문의사항 게시글 수정/삭제

---

src/main/java/com/team/bf/controller/BoardController.java

- [] 기능 추가
- Board controller 중복 맵핑 수정 close #100
-

Board controller 중복 맵핑 수정 close #100

---

src/main/java/com/team/bf/controller/MapAndPlannerController.java
src/main/java/com/team/bf/dao/PlannerDAO.java
src/main/java/com/team/bf/service/PlannerService.java
src/main/java/com/team/bf/service/PlannerServiceImpl.java
src/main/java/com/team/bf/vo/PlannerVO.java
src/main/java/com/team/bf/vo/ResponseVO.java
src/main/resources/mapper/memberMapper.xml
src/main/resources/mapper/plannerMapper.xml

-  여행 플랜 삭제요청 기능
-  여행 플랜 조회 기능
-  여행 플랜에 멤버 초대, 삭제 기능

여행플랜 수정,삭제, 조회기능 추가 close#77

---

src/main/java/com/team/bf/controller/MemberController.java

-  로그인 후 뷰페이지 연결
-  로그아웃 처리 방식 변경 
-  회원가입 후 뷰페이지 연결
-

로그인 회원가입 후 처리 변경 및 마이페이지 문의사항 연결

---

src/main/java/com/team/bf/controller/BoardController.java
src/main/java/com/team/bf/dao/BoardDAO.java
src/main/java/com/team/bf/service/BoardService.java
src/main/java/com/team/bf/service/BoardServiceImpl.java
src/main/resources/mapper/boardMapper.xml

-  마이페이지에서 나의 건의사항 볼 수 있는 뷰페이지 연결
-

마이페이지의 건의사항 뷰페이지 연결

---

src/main/java/com/team/bf/controller/AiController.java
src/main/webapp/js/ai_api.js

feature/openapi-> develop
-  tts 기능 추가
-

TTS 기능 추가 close#78

---

src/main/java/com/team/bf/controller/MapAndPlannerController.java

지도 데이터 요청 방식 추가 및 수정

---

src/main/webapp/WEB-INF/views/map/mapView.jsp
src/main/webapp/css/mapstyle.css

- feature/map-> develop
- 지도 오버레이 뷰 기능 구현
- 마지막 좌표에서만 띄워지는 오류 수정완료
- map뷰와 plan뷰를 ajax로 띄우기
- plan 부분 레이아웃 추가

[FEAT]map뷰 오버레이 기능 구현, plan 부분 레이아웃 추가, plan뷰를 비동기로 만듦

---

src/main/java/com/team/bf/vo/ReviewVO.java
src/main/resources/mapper/reviewMapper.xml

-   ReviewVO에 contentTypeId 추가 -> url 이동시 필요함
-

 ReviewVO에 contentTypeId 추가

---

src/main/java/com/team/bf/vo/ReviewVO.java
src/main/resources/mapper/reviewMapper.xml

ReviewVO에 title 추가 close #111

---

src/main/webapp/WEB-INF/inc/top.jsp
src/main/webapp/WEB-INF/views/community/board.jsp
src/main/webapp/WEB-INF/views/community/boardDetail.jsp
src/main/webapp/WEB-INF/views/community/boardEdit.jsp
src/main/webapp/WEB-INF/views/community/boardForm.jsp
src/main/webapp/css/board.css

- feature/boardView -> develop
- 문의사항 작성 수정 삭제 기능 구현
- 공지/문의사항 페이지 css수정

[FEAT]공지/문의사항 수정

---

src/main/java/com/team/bf/controller/MapAndPlannerController.java
src/main/java/com/team/bf/controller/MemberController.java
src/main/resources/mapper/memberMapper.xml

-   mypage 나의 플래너 Controller 연결
-  boardMapper username 추가
-

mypage 나의 플래너 Controller 연결

---

src/main/java/com/team/bf/controller/BoardController.java
src/main/java/com/team/bf/controller/MapAndPlannerController.java
src/main/java/com/team/bf/controller/MemberController.java
src/main/java/com/team/bf/dao/BoardDAO.java
src/main/java/com/team/bf/service/BoardService.java
src/main/java/com/team/bf/service/BoardServiceImpl.java
src/main/java/com/team/bf/service/OpenApiService.java
src/main/resources/mapper/boardMapper.xml
src/main/webapp/WEB-INF/views/map/mapView.jsp
src/main/webapp/WEB-INF/views/map/mapView2.jsp
src/main/webapp/WEB-INF/views/plan/planView.jsp

myplan 중복 맵핑 삭제

---

src/main/java/com/team/bf/controller/BoardController.java
src/main/java/com/team/bf/dao/BoardDAO.java
src/main/java/com/team/bf/service/BoardService.java
src/main/java/com/team/bf/service/BoardServiceImpl.java
src/main/resources/mapper/boardMapper.xml

문의사항 뷰 Controller 재연결 및 페이지네이션 기능 추가

---

src/main/java/com/team/bf/controller/MapAndPlannerController.java

mypage 나의 플래너 url 수정

---

src/main/java/com/team/bf/controller/MemberController.java
src/main/java/com/team/bf/dao/MemberDAO.java
src/main/java/com/team/bf/service/MemberService.java
src/main/java/com/team/bf/service/MemberServiceImpl.java
src/main/resources/mapper/memberMapper.xml

회원정보 업데이트 기능 추가 close #104

---

src/main/java/com/team/bf/controller/BoardController.java
src/main/resources/mapper/boardMapper.xml

-   mypage 나의 건의사항 답변과 함께 불러오기 기능 추가
-

mypage 나의 건의사항 답변과 함께 불러오기 기능 추가 close #106

---

src/main/java/com/team/bf/interceptor/AdminInterceptor.java
src/main/java/com/team/bf/interceptor/LoginInterceptor.java
src/main/java/com/team/bf/interceptor/ServerConfigure.java

feature/interceptor-> develop
- login, admin Interceptor 추가

login, admin Interceptor 추가

---

src/main/java/com/team/bf/controller/AccommodationController.java
src/main/java/com/team/bf/service/OpenApiService.java

feature/tour_information-> develop
-   숙박정보 리스트뷰, 상세 뷰 데이터 전달

숙박정보 리스트뷰, 상세 뷰 데이터 전달

---

src/main/java/com/team/bf/controller/AccommodationController.java
src/main/java/com/team/bf/controller/TourLocationController.java
src/main/java/com/team/bf/dao/ReviewDAO.java
src/main/java/com/team/bf/service/OpenApiService.java
src/main/java/com/team/bf/service/ReviewService.java
src/main/resources/mapper/reviewMapper.xml
src/main/webapp/WEB-INF/views/travel_information/travel_informationPage.jsp

feature/tour_information-> develop
-   여행지 정보 뷰 연결 및 데이터 전송 기능 추가

여행지 정보 뷰 연결 및 데이터 전송 기능 추가 close #127

---

src/main/java/com/team/bf/controller/ReviewController.java

feature/review-> develop
-   myreview에 pvo객체 추가 (페이지 네이션에 필요)
-

ReviewController -> myreview에 pvo객체 추가

---

src/main/java/com/team/bf/controller/AdminController.java
src/main/webapp/WEB-INF/views/admin/board.jsp
src/main/webapp/WEB-INF/views/mypage/mypage.jsp

feature/map-> develop
- 관리자 로그인 후 페이지 이동 안됨 수정
-

관리자 로그인 후 페이지 이동 안됨 수정

---

src/main/java/com/team/bf/controller/AccommodationController.java
src/main/java/com/team/bf/controller/TourLocationController.java

feature/tour_information-> develop
- 여행, 숙박정보 리뷰 없을 시 리뷰 정보 전달 안됨

[FEAT] 여행, 숙박정보 리뷰 없을 시 리뷰 정보 전달 안됨

---

src/main/java/com/team/bf/controller/BoardController.java
src/main/java/com/team/bf/controller/ReviewController.java

- 마이페이지 리뷰, 문의사항 default pageCount 변경

[STYLE] 마이페이지 리뷰, 문의사항 default pageCount 변경

---

src/main/webapp/css/introductionstyle.css

feature/new_accommo_travel-> develop
- 소개페이지 css 수정
-

소개페이지 CSS수정

---

src/main/webapp/WEB-INF/inc/top.jsp
src/main/webapp/WEB-INF/views/admin/board.jsp
src/main/webapp/WEB-INF/views/community/board.jsp
src/main/webapp/WEB-INF/views/community/boardDetail.jsp
src/main/webapp/WEB-INF/views/community/boardForm.jsp
src/main/webapp/WEB-INF/views/coordinator/coordinator.jsp
src/main/webapp/css/board.css
src/main/webapp/css/bottom.css
src/main/webapp/css/home.css
src/main/webapp/css/top.css

feature/adminView -> develop
- 관리자페이지 생성, 탑, 바텀 수정

[FEAT]관리자페이지생성, 탑, 바텀 수정

---

src/main/java/com/team/bf/controller/AdminController.java
src/main/java/com/team/bf/controller/CoordinatorController.java
src/main/java/com/team/bf/dao/CoordinatorDAO.java
src/main/java/com/team/bf/service/CoordinatorService.java
src/main/java/com/team/bf/service/CoordinatorServiceImpl.java
src/main/resources/mapper/coordinatorMapper.xml
src/main/webapp/WEB-INF/views/coordinator/coordinator.jsp
src/main/webapp/WEB-INF/views/coordinator/coordinatorForm.jsp

- 코디네이터 리스트, 코디네이터 등록(관리자) 뷰 연결

코디네이터 리스트, 코디네이터 등록(관리자) 뷰 연결

---

src/main/java/com/team/bf/HomeController.java
src/main/java/com/team/bf/controller/AccommodationController.java
src/main/java/com/team/bf/controller/CoordinatorController.java
src/main/java/com/team/bf/controller/TourLocationController.java
src/main/java/com/team/bf/service/OpenApiService.java

- amdin 오타수정,
- 숙박, 여행지 시군구 코드 조회 가능

amdin 오타수정, 숙박, 여행지 시군구 코드 조회 가능

---

src/main/java/com/team/bf/controller/AdminController.java
src/main/webapp/WEB-INF/views/admin/memberList.jsp

관리자 회원 삭제 기능 추가

---

src/main/webapp/WEB-INF/views/map/mapView.jsp
src/main/webapp/css/mapstyle.css

feature/map-> develop
- plan 리스트 레이아웃 수정, 리스트 DB 저장 구현

[FEAT]plan 리스트 레이아웃 수정, 리스트 DB 저장 구현

---

src/main/java/com/team/bf/dao/PlannerDAO.java
src/main/java/com/team/bf/service/OpenApiService.java
src/main/java/com/team/bf/service/PlannerService.java
src/main/java/com/team/bf/service/PlannerServiceImpl.java
src/main/java/com/team/bf/vo/PlannerVO.java
src/main/resources/mapper/plannerMapper.xml

- 플래너 불러오기 기능 수정
-  openapi 주소, 맵위치 추가

플래너 불러오기 기능 수정, openapi 주소, 맵위치 추가

---

src/main/java/com/team/bf/controller/MapAndPlannerController.java

- MapAndPlannerController 여행계획 1개 데이터 불러오기 기능 추가

MapAndPlannerController 여행계획 1개 데이터 불러오기 기능 추가

---

src/main/webapp/WEB-INF/views/map/mapView.jsp
src/main/webapp/css/mapstyle.css

feature/map -> develop
- plan 리스트 기능수정
- plan 불러오기 기능
- 날짜 유효성 검사

[FEAT]plan 리스트추가 기능수정, plan 불러오기 기능구현

---

src/main/java/com/team/bf/controller/BoardController.java
src/main/java/com/team/bf/controller/CoordinatorController.java
src/main/webapp/WEB-INF/views/admin/coordinatorForm.jsp
src/main/webapp/WEB-INF/views/community/boardEdit.jsp
src/main/webapp/WEB-INF/views/coordinator/coordinatorForm.jsp

feature/main -> develop
- 보드컨트롤러 링크 수정 및 코디네이터 연결 스크립트 수정

[FEAT] boardcontroller, cordinator 수정

---

src/main/webapp/WEB-INF/views/mypage/myplan.jsp

-  마이페이지 -> 마이플래너에서 여행계획중 하나 클릭시 지도로 이동하면서 데이터 불러오기 기능 추가

마이페이지에서->지도 여행 계획 불러오기 기능 추가

---

src/main/webapp/WEB-INF/views/admin/board.jsp
src/main/webapp/WEB-INF/views/admin/boardFormReply.jsp
src/main/webapp/WEB-INF/views/community/boardDetail.jsp

feature/admin -> develop
- 관리자 문의/게시글 관리 뷰 수정

관리자 문의/게시글 관리 뷰 수정

---

src/main/webapp/WEB-INF/views/home.jsp

feature/main-> develop
- 메인페이지 숙소 별점 추가

[FEAT]메인페이지 숙소 별점 추가

---

src/main/webapp/css/myplanner.css
src/main/webapp/css/myqna.css

mypage CSS 수정

---

src/main/webapp/WEB-INF/views/map/mapView.jsp
src/main/webapp/css/mapstyle.css

feature/map-> develop
- 모달창 구현중

[FEAT]모달 레이아웃 구현중

---

src/main/webapp/WEB-INF/views/community/suggestEdit.jsp
src/main/webapp/css/myreview.css

마이리뷰 css 건의할래요 버튼위치 수정

---

src/main/webapp/WEB-INF/views/map/mapView.jsp
src/main/webapp/css/mapstyle.css

feature/map -> develop
- 로그아웃 상태일때 리스트 추가 뜨는 것 수정

[FIX]로그아웃 상태일때 리스트 추가 뜨는 것 수정

---

src/main/webapp/WEB-INF/inc/top.jsp

feature/main-> develop
- top.jsp 관리자모드 이동수단 등록 메뉴 추가
-

[FEAT]top.jsp 관리자 수정

---

src/main/webapp/WEB-INF/views/map/mapView.jsp
src/main/webapp/css/mapstyle.css

feature/map -> develop
- 리스트 배경 겹치는 것 수정

[FIX] 리스트 배경 겹치는 것 수정
